services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - caddynet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /opt/not-backed-up-volumes/qbittorrent/appdata:/config
      - /opt/not-backed-up-volumes/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  caddynet:
    external: true
    name: caddynet
