services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - qbittorrent_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /opt/not-backed-up-volumes/qbittorrent/appdata:/config
      - /opt/not-backed-up-volumes/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "managed-by=pipeline"
networks:
  qbittorrent_net:
    external: true
    name: qbittorrent_net
