networks:
  invio_net:
    external: true
    name: invio_net

services:
  backend:
    container_name: invio-backend
    image: ghcr.io/kittendevv/invio-backend:latest
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    shm_size: '256m'
#    env_file:
#      - .env
    environment:
      ADMIN_USER: ${INVIO_ADMIN_USER}
      ADMIN_PASS: ${INVIO_ADMIN_PASS}
      JWT_SECRET: ${INVIO_JWT_SECRET}
#      DATABASE_PATH: ${INVIO_DATABASE_PATH:-/app/data/invio.db}
    volumes:
      - /opt/backed-up-volumes/invio/data:/app/data
      - /opt/not-backed-up-volumes/invio-cache:/.cache
    restart: unless-stopped
    networks:
      - invio_net
    healthcheck:
      test: ["CMD-SHELL", "deno eval 'const r=await fetch(\"http://localhost:3000/\");Deno.exit(r.status<500?0:1);'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "managed-by=pipeline"

  frontend:
    container_name: invio-frontend
    image: ghcr.io/kittendevv/invio-frontend:latest
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
#    env_file:
#      - .env
    environment:
#      PORT: ${FRONTEND_PORT_INTERNAL:-8000}
      BACKEND_URL: ${BACKEND_URL:-http://invio-backend:3000}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - invio_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "managed-by=pipeline"
