version: '3.9'

networks:
  caddynet:
    external: true
    name: caddynet

services:
  backend:
    container_name: invio-backend
    image: ghcr.io/kittendevv/invio-backend:latest
    env_file:
      - .env
    environment:
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PATH: ${DATABASE_PATH:-/app/data/invio.db}
    volumes:
      - /opt/backed-up-volumes/invio/data:/app/data
    restart: unless-stopped
    networks:
      - caddynet
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "com.centurylinklabs.watchtower.monitor-only=true"

  frontend:
    container_name: invio-frontend
    image: ghcr.io/kittendevv/invio-frontend:latest
    env_file:
      - .env
    environment:
      PORT: ${FRONTEND_PORT_INTERNAL:-8000}
      BACKEND_URL: ${BACKEND_URL:-http://invio-backend:3000}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - caddynet
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "com.centurylinklabs.watchtower.monitor-only=true"
