services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: unless-stopped
    networks:
      - caddynet
    environment:
      - TZ=Australia/Melbourne  # Change to your time zone
      - PLEX_CLAIM=claim-${PLEX_CLAIM}           # Optional: for linking to your Plex account
    volumes:
      - /home/nathangemmill/plex/config:/config
      - /home/nathangemmill/plex/media:/media
    devices:
      - /dev/dri:/dev/dri       # (Optional) For hardware transcoding
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "managed-by=pipeline"
networks:
  caddynet:
    external: true
    name: caddynet
