services:
  it-tools:
    image: corentinth/it-tools:nightly
    container_name: it-tools
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "managed-by=pipeline"
    networks:
      - caddynet
    restart: unless-stopped

networks:
  caddynet:
    external: true
    name: caddynet
