services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    security_opt:
      - no-new-privileges:true
    labels:
      - "managed-by=pipeline"
    networks:
      - it_tools_net
    restart: unless-stopped

networks:
  it_tools_net:
    external: true
    name: it_tools_net
