services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    user: "1000:1000"
    networks:
      - caddynet
    environment:
      DOMAIN: "https://bw.itgo.com.au"  # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "false" # Deactivate this with "false" after you have created your account so that no strangers can register
      SMTP_HOST: ${SMTP_HOST} # Your SMTP server host
      SMTP_PORT: ${SMTP_PORT} # Typically 587 for TLS/STARTTLS, or 465 for SSL/TLS
      SMTP_FROM_NAME: 'Vaultwarden' # Name to appear in "From" field
      SMTP_FROM_EMAIL: 'credentials@itgo.com.au' # Email address for "From" field
      SMTP_USERNAME: ${SMTP_USER} # Your SMTP username
      SMTP_PASSWORD: ${SMTP_PASSWORD} # Your SMTP password (use app passwords for services like Gmail)
      SMTP_TLS: 'true' # Set to 'true' if using STARTTLS (Port 587)
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
    volumes:
      - /opt/backed-up-volumes/vaultwarden/vw-data:/data # the path before the : can be changed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "managed-by=pipeline"
#    ports:
#      - 11001:80 # you can replace the 11001 with your preferred port
networks:
  caddynet:
    external: true
    name: caddynet
