services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    networks:
      - caddynet
    environment:
      DOMAIN: "https://bw.itgo.com.au"  # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "false" # Deactivate this with "false" after you have created your account so that no strangers can register
      SMTP_HOST: 'mail.smtp2go.com' # Your SMTP server host
      SMTP_PORT: '587' # Typically 587 for TLS/STARTTLS, or 465 for SSL/TLS
      SMTP_FROM_NAME: 'Vaultwarden' # Name to appear in "From" field
      SMTP_FROM_EMAIL: 'credentials@itgo.com.au' # Email address for "From" field
      SMTP_USERNAME: 'itgo.com.au' # Your SMTP username
      SMTP_PASSWORD: ${smtp_2_go_pass} # Your SMTP password (use app passwords for services like Gmail)
      SMTP_TLS: 'true' # Set to 'true' if using STARTTLS (Port 587)
      ADMIN_TOKEN: ${admin_token}
    volumes:
      - /opt/backed-up-volumes/vaultwarden/vw-data:/data # the path before the : can be changed
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
#    ports:
#      - 11001:80 # you can replace the 11001 with your preferred port
networks:
  caddynet:
    external: true
    name: caddynet
