services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    networks:
     - caddynet
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "managed-by=pipeline"
networks:
  caddynet:
    external: true
    name: caddynet
