services:
  papra:
    build:
      context: https://github.com/nathangemmill/papra.git
      dockerfile: packages/app/Dockerfile
    container_name: papra
    restart: unless-stopped
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    environment:
      - APP_BASE_URL=https://papra.internal.itgo.com.au
      - AUTH_SECRET=${PAPRA_AUTH_SECRET}
      - AUTH_IS_REGISTRATION_ENABLED=false
      - EMAILS_FROM_ADDRESS=${PAPRA_EMAILS_FROM_ADDRESS}
      - EMAILS_DRIVER=smtp
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=true
      - DOCUMENT_STORAGE_MAX_UPLOAD_SIZE=0
    volumes:
      - /opt/backed-up-volumes/papra/data:/app/app-data
    networks:
      - papra_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "managed-by=pipeline"

networks:
  papra_net:
    external: true
    name: papra_net
